[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
evm_version = "cancun"
optimizer_runs = 1000000
via_ir = true

[profile.ci]
verbosity = 4

[profile.coverage]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true